import { Home, LayoutTemplate, Settings, Trash } from "lucide-react";
import { Theme } from "./types";

export const data = {
    user: {
        name: "Aryan Baadlas",
        email: "aryanbaadals@gmail.com",
        avatar: "/logo.jpg",
    },

    navMain: [
        {
            title: "Home",
            url: "/",
            icon: Home,
            isActive: true,
        },
        {
            title: "Templates",
            url: "/templates",
            icon: LayoutTemplate,
            isActive: false,
        },
        {
            title: "Trash",
            url: "/trash",
            icon: Trash,
            isActive: false,
        },
        {
            title: "Settings",
            url: "/settings",
            icon: Settings,
            isActive: false,
        },
    ],
};

export const containerVaraints = {
    hidden: {
        opacity: 0,
    },
    visible: {
        opacity: 1,
        transition: {
            staggerChildren: 0.1,
        },
    },
};

export const itemVatiants = {
    hidden: {
        opacity: 0,
        y: 20,
    },
    visible: {
        opacity: 1,
        y: 0,
        transition: { type: "spring", stiffness: 100 },
    },
};

export const themes: Theme[] = [
    {
        name: "Dark Mode",
        fontFamily: "'Roboto', sans-serif",
        fontColor: "#fff",
        backgroundColor: "#121212",
        slideBackgroundColor: "#1E1E1E",
        accentColor: "#BB86FC",
        navbarColor: "#1F1F1F",
        sidebarColor: "#1F1F1F",
        type: "dark",
    },
    {
        name: "Ocean Breeze",
        fontFamily: "'Poppins', sans-serif",
        fontColor: "#2E3A59",
        backgroundColor: "#A3D8FF",
        slideBackgroundColor: "#E1F4FF",
        accentColor: "#00A9E0",
        navbarColor: "#ffffff",
        sidebarColor: "#A3D8FF",
        type: "light",
    },
    {
        name: "Solar Flare",
        fontFamily: "'Montserrat', sans-serif",
        fontColor: "#ffffff",
        backgroundColor: "#FF6F00",
        slideBackgroundColor: "#FF9800",
        accentColor: "#FFD740",
        navbarColor: "#FF6F00",
        sidebarColor: "#FF7043",
        type: "light",
    },
    {
        name: "Forest Retreat",
        fontFamily: "'Lora', serif",
        fontColor: "#3E4A4F",
        backgroundColor: "#2A4C34",
        slideBackgroundColor: "#4E735A",
        accentColor: "#7A9A92",
        navbarColor: "#ffffff",
        sidebarColor: "#2A4C34",
        type: "dark",
    },
    {
        name: "Vintage Paper",
        fontFamily: "'Merriweather', serif",
        fontColor: "#3E2A47",
        backgroundColor: "#F4E1D2",
        slideBackgroundColor: "#E0C8A0",
        accentColor: "#D85C3A",
        navbarColor: "#F4E1D2",
        sidebarColor: "#F4E1D2",
        type: "light",
    },
    {
        name: "Neon Lights",
        fontFamily: "'Futura', sans-serif",
        fontColor: "#000",
        backgroundColor: "#212121",
        slideBackgroundColor: "#2C2C2C",
        accentColor: "#39FF14",
        navbarColor: "#000",
        sidebarColor: "#212121",
        type: "dark",
    },
    {
        name: "Modern Elegance",
        fontFamily: "'Lato', sans-serif",
        fontColor: "#444",
        backgroundColor: "#F7F7F7",
        slideBackgroundColor: "#E9E9E9",
        accentColor: "#FF6F61",
        navbarColor: "#FFFFFF",
        sidebarColor: "#F7F7F7",
        type: "light",
    },
    {
        name: "Sunset Glow",
        fontFamily: "'Playfair Display', serif",
        fontColor: "#FFF",
        backgroundColor: "#FF7F50",
        slideBackgroundColor: "#FFD700",
        accentColor: "#FF4500",
        navbarColor: "#FF6347",
        sidebarColor: "#FF7F50",
        type: "light",
    },
    {
        name: "Mossy Stone",
        fontFamily: "'Nunito', sans-serif",
        fontColor: "#3D3D3D",
        backgroundColor: "#8A9A5B",
        slideBackgroundColor: "#C2D38D",
        accentColor: "#A6B84E",
        navbarColor: "#4C5B27",
        sidebarColor: "#8A9A5B",
        type: "light",
    },
    {
        name: "Royal Luxe",
        fontFamily: "'Baskerville', serif",
        fontColor: "#D1B5A3",
        backgroundColor: "#3A1E2A",
        slideBackgroundColor: "#5A2D41",
        accentColor: "#C79792",
        navbarColor: "#3A1E2A",
        sidebarColor: "#5A2D41",
        type: "dark",
    },
    {
        name: "Minty Fresh",
        fontFamily: "'Arial', sans-serif",
        fontColor: "#2A3D36",
        backgroundColor: "#C1E1C1",
        slideBackgroundColor: "#A0D8A0",
        accentColor: "#00B37E",
        navbarColor: "#ffffff",
        sidebarColor: "#C1E1C1",
        type: "light",
    },
    {
        name: "Monochrome Chic",
        fontFamily: "'Arial', sans-serif",
        fontColor: "#000000",
        backgroundColor: "#E5E5E5",
        slideBackgroundColor: "#C4C4C4",
        accentColor: "#333333",
        navbarColor: "#ffffff",
        sidebarColor: "#E5E5E5",
        type: "light",
    },
    {
        name: "Coral Reef",
        fontFamily: "'Verdana', sans-serif",
        fontColor: "#FFFFFF",
        backgroundColor: "#FF7F50",
        slideBackgroundColor: "#FF6347",
        accentColor: "#F4A261",
        navbarColor: "#FF6347",
        sidebarColor: "#FF7F50",
        type: "light",
    },
    {
        name: "Night Sky",
        fontFamily: "'Helvetica', sans-serif",
        fontColor: "#F0F0F0",
        backgroundColor: "#1A1A2E",
        slideBackgroundColor: "#162447",
        accentColor: "#00A8CC",
        navbarColor: "#162447",
        sidebarColor: "#1A1A2E",
        type: "dark",
    },
    {
        name: "Lavender Dream",
        fontFamily: "'Georgia', serif",
        fontColor: "#000",
        backgroundColor: "#E6E6FA",
        slideBackgroundColor: "#D8B7DD",
        accentColor: "#8A2BE2",
        navbarColor: "#E6E6FA",
        sidebarColor: "#D8B7DD",
        type: "light",
    },
    {
        name: "Tropical Paradise",
        fontFamily: "'Tisa', serif",
        fontColor: "#212121",
        backgroundColor: "#FF6F61",
        slideBackgroundColor: "#FF9F69",
        accentColor: "#F5A623",
        navbarColor: "#FF6F61",
        sidebarColor: "#FF9F69",
        type: "light",
    },
    {
        name: "Frozen Tundra",
        fontFamily: "'Arial', sans-serif",
        fontColor: "#0A0A0A",
        backgroundColor: "#B0C4DE",
        slideBackgroundColor: "#C0D9E4",
        accentColor: "#4682B4",
        navbarColor: "#B0C4DE",
        sidebarColor: "#C0D9E4",
        type: "light",
    },
    {
        name: "Autumn Leaves",
        fontFamily: "'Quicksand', sans-serif",
        fontColor: "#333",
        backgroundColor: "#FF8C00",
        slideBackgroundColor: "#F1C27D",
        accentColor: "#FF6347",
        navbarColor: "#FF8C00",
        sidebarColor: "#F1C27D",
        type: "light",
    },
    {
        name: "Cosmic Vibe",
        fontFamily: "'Source Sans Pro', sans-serif",
        fontColor: "#F1F1F1",
        backgroundColor: "#2F4F4F",
        slideBackgroundColor: "#4B0082",
        accentColor: "#8A2BE2",
        navbarColor: "#2F4F4F",
        sidebarColor: "#4B0082",
        type: "dark",
    },
    {
        name: "Blush Pink",
        fontFamily: "'Tisa', serif",
        fontColor: "#FFF",
        backgroundColor: "#F7D1D1",
        slideBackgroundColor: "#F1A7C2",
        accentColor: "#FFB6C1",
        navbarColor: "#F7D1D1",
        sidebarColor: "#F1A7C2",
        type: "light",
    },
];
